version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - echo "Build started on `date`"
      - mkdir -p dist
      - cp index.html style.css app.js dist/
artifacts:
  files:
    - dist/**/*
